/***********************************************************************
Copyright 2019 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Note that these code samples being shared are not official Google
products and are not formally supported.
************************************************************************/

/**
 * @fileoverview Objects mirroring SDF objects structure to enable sheets setup.
 */

/**
 * Main variable containing SDF objects descriptions.
 * For each object we list a series of arrays composed by [field name, default
 * value, cell background color].
 */
var SDF = [
  {
    'name': 'IO-SDF',
    'fields': [
      ['Io Id', 'ext111', 'lightblue'],
      ['Campaign Id', '', 'yellow'],
      ['Name', 'Automated TrueView IO', 'lightgreen'],
      ['Timestamp', '', ''],
      ['Status', 'Active', ''],
      ['Io Type', 'Standard', ''],
      ['Fees', '', ''],
      ['Integration Code', '', ''],
      ['Details', '', ''],
      ['Pacing', 'Flight', ''],
      ['Pacing Rate', 'ASAP', ''],
      ['Pacing Amount', '0', ''],
      ['Frequency Enabled', 'FALSE', ''],
      ['Frequency Exposures', '0', ''],
      ['Frequency Period', '0', ''],
      ['Frequency Amount', '0', ''],
      ['Performance Goal Type', 'None', ''],
      ['Performance Goal Value', '0', ''],
      ['Measure DAR', 'False', ''],
      ['Measure DAR Channel', '', ''],
      ['Budget Type', 'Amount', ''],
      ['Budget Segments', '(5.00;04/01/2017;06/30/2017;);', ''],
      ['Auto Budget Allocation', 'False', ''],
      ['Geography Targeting - Include', '', ''],
      ['Geography Targeting - Exclude', '', ''],
      ['Language Targeting - Include', '', ''],
      ['Language Targeting - Exclude', '', ''],
      ['Device Targeting - Include', '', ''],
      ['Device Targeting - Exclude', '', ''],
      ['Browser Targeting - Include', '', ''],
      ['Browser Targeting - Exclude', '', ''],
      ['Brand Safety Labels', '', ''],
      ['Brand Safety Sensitivity Setting', 'Do not block', ''],
      ['Brand Safety Custom Settings', '', ''],
      ['Third Party Verification Services', 'None', ''],
      ['Third Party Verification Labels', '', ''],
      ['Channel Targeting - Include', '', ''],
      ['Channel Targeting - Exclude', '', ''],
      ['Site Targeting - Include', '', ''],
      ['Site Targeting - Exclude', '', ''],
      ['App Targeting - Include', '', ''],
      ['App Targeting - Exclude', '', ''],
      ['App Collection Targeting - Include', '', ''],
      ['App Collection Targeting - Exclude', '', ''],
      ['Category Targeting - Include', '', ''],
      ['Category Targeting - Exclude', '', ''],
      ['Keyword Targeting - Include', '', ''],
      ['Keyword Targeting - Exclude', '', ''],
      ['Keyword List Targeting - Exclude', '', ''],
      ['Audience Targeting - Similar Audiences', 'False', ''],
      ['Audience Targeting - Include', '', ''],
      ['Audience Targeting - Exclude', '', ''],
      ['Affinity & In Market Targeting - Include', '', ''],
      ['Affinity & In Market Targeting - Exclude', '', ''],
      ['Custom List Targeting', '', ''],
      ['Inventory Source Targeting - Authorized Seller Only', 'FALSE', ''],
      ['Inventory Source Targeting - Include', '', ''],
      ['Inventory Source Targeting - Exclude', '', ''],
      ['Inventory Source Targeting - Target New Exchanges', '', ''],
      ['Daypart Targeting', '', ''],
      ['Daypart Targeting Time Zone', '', ''],
      ['Environment Targeting', 'Desktop Web; Mobile Web; Desktop Web Video; Mobile App', 'yellow'],
      ['Viewability Targeting Active View', '', ''],
      ['Viewability Targeting Ad Position - Include', '', ''],
      ['Viewability Targeting Ad Position - Exclude', '', ''],
      ['Video Ad Position Targeting', '', ''],
      ['Video Player Size Targeting', '', ''],
      ['Demographic Targeting Gender', '', ''],
      ['Demographic Targeting Age', '', ''],
      ['Demographic Targeting Household Income', '', ''],
      ['Demographic Targeting Parental Status', '', ''],
      ['Connection Speed Targeting', '', ''],
      ['Carrier Targeting - Include', '', ''],
      ['Carrier Targeting - Exclude', '', ''],
    ]
  },
  {
    'name': 'LI-SDF',
    'fields': [
      ['Line Item Id', 'ext2%%ID%%', 'lightblue'],
      ['Io Id', 'ext111', 'lightblue'],
      ['Type', 'TrueView', ''],
      ['Subtype', 'Simple', ''],
      ['Name', 'Line Item %%NAME%%', 'lightblue'],
      ['Timestamp', '', ''],
      ['Status', 'Active', ''],
      ['Start Date', '04/01/2017 00:00', 'yellow'],
      ['End Date', '05/01/2017 00:00', 'yellow'],
      ['Budget Type', 'TrueView Daily Budget', ''],
      ['Budget Amount', '', ''],
      ['Pacing', 'Daily', ''],
      ['Pacing Rate', 'ASAP', ''],
      ['Pacing Amount', '1', ''],
      ['Frequency Enabled', 'False', ''],
      ['Frequency Exposures', '0', ''],
      ['Frequency Period', 'Minutes', ''],
      ['Frequency Amount', '', ''],
      ['TrueView View Frequency Enabled', 'False', ''],
      ['TrueView View Frequency Exposures', '', ''],
      ['TrueView View Frequency Period', '', ''],
      ['Partner Revenue Model', 'TMCM', ''],
      ['Partner Revenue Amount', '0', ''],
      ['Conversion Counting Type', '', ''],
      ['Conversion Counting Pct', '', ''],
      ['Conversion Pixel Ids', '', ''],
      ['Fees', '', ''],
      ['Integration Code', '', ''],
      ['Details', '', ''],
      ['Bid Strategy Type', '', ''],
      ['Bid Strategy Value', '', ''],
      ['Bid Strategy Unit', '', ''],
      ['Bid Strategy Do Not Exceed', '', ''],
      ['Creative Assignments', '', ''],
      ['Geography Targeting - Include', '', ''],
      ['Geography Targeting - Exclude', '', ''],
      ['Language Targeting - Include', '', ''],
      ['Language Targeting - Exclude', '', ''],
      ['Device Targeting - Include', '', ''],
      ['Device Targeting - Exclude', '', ''],
      ['Browser Targeting - Include', '', ''],
      ['Browser Targeting - Exclude', '', ''],
      ['Brand Safety Labels', '', ''],
      ['Brand Safety Sensitivity Setting', '', ''],
      ['Brand Safety Custom Settings', '', ''],
      ['Third Party Verification Services', '', ''],
      ['Third Party Verification Labels', '', ''],
      ['Channel Targeting - Include', '', ''],
      ['Channel Targeting - Exclude', '', ''],
      ['Site Targeting - Include', '', ''],
      ['Site Targeting - Exclude', '', ''],
      ['App Targeting - Include', '', ''],
      ['App Targeting - Exclude', '', ''],
      ['App Collection Targeting - Include', '', ''],
      ['App Collection Targeting - Exclude', '', ''],
      ['Category Targeting - Include', '', ''],
      ['Category Targeting - Exclude', '', ''],
      ['Keyword Targeting - Include', '', ''],
      ['Keyword Targeting - Exclude', '', ''],
      ['Keyword List Targeting - Exclude', '', ''],
      ['Audience Targeting - Similar Audiences', '', ''],
      ['Audience Targeting - Include', '', ''],
      ['Audience Targeting - Exclude', '', ''],
      ['Affinity & In Market Targeting - Include', '', ''],
      ['Affinity & In Market Targeting - Exclude', '', ''],
      ['Custom List Targeting', '', ''],
      ['Inventory Source Targeting - Authorized Seller Only', '', ''],
      ['Inventory Source Targeting - Include', '', ''],
      ['Inventory Source Targeting - Exclude', '', ''],
      ['Inventory Source Targeting - Target New Exchanges', '', ''],
      ['Daypart Targeting', '', ''],
      ['Daypart Targeting Time Zone', '', ''],
      ['Environment Targeting', '', ''],
      ['Viewability Targeting Active View', '', ''],
      ['Viewability Targeting Ad Position - Include', '', ''],
      ['Viewability Targeting Ad Position - Exclude', '', ''],
      ['Video Ad Position Targeting', '', ''],
      ['Video Player Size Targeting', '', ''],
      ['Demographic Targeting Gender', '', ''],
      ['Demographic Targeting Age', '', ''],
      ['Demographic Targeting Household Income', '', ''],
      ['Demographic Targeting Parental Status', '', ''],
      ['Connection Speed Targeting', '', ''],
      ['Carrier Targeting - Include', '', ''],
      ['Carrier Targeting - Exclude', '', ''],
      ['Bid Multipliers', '', ''],
      ['TrueView Video Ad Formats', 'In-stream / Video Discovery', ''],
      ['TrueView Mobile Bid Adjustment Option', '', ''],
      ['TrueView Mobile Bid Adjustment Percentage', '', ''],
      ['TrueView Desktop Bid Adjustment Option', '', ''],
      ['TrueView Desktop Bid Adjustment Percentage', '', ''],
      ['TrueView Tablet Bid Adjustment Option', '', ''],
      ['TrueView Tablet Bid Adjustment Percentage', '', ''],
      ['TrueView Category Exclusions Targeting', '', ''],
      ['TrueView Content Filter', 'Standard', ''],
      ['TrueView Inventory Source Targeting',
       'YouTube Search; YouTube Videos; Video Partners;', ''],
    ]
  },
  {
    'name': 'AdGroup-SDF',
    'fields': [
      ['Ad Group Id', 'ext3%%ID%%', 'lightblue'],
      ['Line Item Id', 'ext2%%ID%%', 'lightblue'],
      ['Name', 'Ad Group %%NAME%%', 'lightblue'],
      ['Status', 'Active', ''],
      ['Video Ad Format', 'In-stream', ''],
      ['Max Cost Per View', '1.0', ''],
      ['Popular Videos Bid Adjustment', '50', ''],
      ['Keyword Targeting - Include', '', ''],
      ['Keyword Targeting - Exclude', '', ''],
      ['Category Targeting - Include', '', ''],
      ['Category Targeting - Exclude', '', ''],
      ['Placement Targeting - YouTube Channels - Include', '', ''],
      ['Placement Targeting - YouTube Channels - Exclude', '', ''],
      ['Placement Targeting - YouTube Videos - Include', '', ''],
      ['Placement Targeting - YouTube Videos - Exclude', '', ''],
      ['Placement Targeting - Urls - Include', '', ''],
      ['Placement Targeting - Urls - Exclude', '', ''],
      ['Placement Targeting - Apps - Include', '', ''],
      ['Placement Targeting - Apps - Exclude', '', ''],
      ['Placement Targeting - App Collections - Include', '', ''],
      ['Placement Targeting - App Collections - Exclude', '', ''],
      ['Demographic Targeting Gender', 'Male; Female; Unknown;', 'yellow'],
      ['Demographic Targeting Age',
       '18-24; 25-34; 35-44; 45-54; 55-64; 65+; Unknown;', 'yellow'],
      ['Demographic Targeting Household Income',
       'Top 10%; 11-20%; 21-30%; 31-40%; 41-50%; Lower 50%; Unknown;', ''],
      ['Demographic Targeting Parental Status',
       'Not a parent; Parent; Unknown;', 'yellow'],
      ['Audience Targeting - Include', '', ''],
      ['Audience Targeting - Exclude', '', ''],
      ['Affinity & In Market Targeting - Include', '', ''],
      ['Affinity & In Market Targeting - Exclude', '', ''],
      ['Custom List Targeting', '', ''],
    ]
  },
  {
    'name': 'Ad-SDF',
    'fields': [
      ['Ad Id', '', ''],
      ['Ad Group Id', 'ext3%%ID%%', 'lightblue'],
      ['Name', 'Ad %%NAME%%', 'lightblue'],
      ['Status', 'Active', ''],
      ['Video Id', '%%YOUTUBE_ID%%', 'lightblue'],
      ['In-stream Display Url', '%%DISPLAY_URL%%', 'lightblue'],
      ['In-stream Landing Page Url', '%%LANDING_URL%%', 'lightblue'],
      ['DCM Tracking - Placement Id', '', ''],
      ['DCM Tracking - Ad Id', '', ''],
      ['DCM Tracking - Creative Id', '', ''],
      ['Click Tracker URL', '', ''],
      ['In-stream Custom Parameters', '', ''],
      ['Video Discovery Video Thumbnail', '', ''],
      ['Video Discovery Headline', '', ''],
      ['Video Discovery Description 1', '', ''],
      ['Video Discovery Description 2', '', ''],
      ['Video Discovery Landing Page', '', ''],
    ]
  }
];
